name: pfds
version: '0.1.0.0'
category: Learning
author: maton
maintainer: automatonix@gmail.com
copyright: 2017 maton
license: BSD3
github: matonix/pfds
extra-source-files: README.md

library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5

executables:
  graphviz:
    main: Viz.hs
    source-dirs: app
    dependencies:
    - base
    - pfds
    - fgl
    - fgl-visualize
    - process
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  trace:
    main: Trace.hs
    source-dirs: app
    dependencies:
    - base
    - pfds
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  pfds-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - pfds
    - hspec
    - QuickCheck
